services:
  postgres:
    image: postgres:17
    container_name: rozetka-unified-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rozetka_unified
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rozetka_unified_postgres_data:/var/lib/postgresql/data

volumes:
  rozetka_unified_postgres_data:
